services:
  - type: web
    name: assistly-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://YOUR-BACKEND-URL/api/v1
      - key: NEXT_PUBLIC_APP_URL
        value: https://assistly-frontend.onrender.com

